import type { IconType } from 'react-icons';
import {
  SiAngular,
  SiDocker,
  SiExpress,
  SiFigma,
  SiJavascript,
  SiJest,
  SiLaravel,
  SiMantine,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPrimeng,
  SiReact,
  SiReactivex,
  SiReactquery,
  SiRedux,
  SiSass,
  SiSentry,
  SiShadcnui,
  SiTailwindcss,
  SiTypescript,
  SiVitest,
} from 'react-icons/si';

export type Tech = { name: string; Icon: IconType; color: string };

/** Ordered list used by the tech marquee. */
export const techLogos: Tech[] = [
  { name: 'TypeScript', Icon: SiTypescript, color: '#3178C6' },
  { name: 'Angular', Icon: SiAngular, color: '#DD0031' },
  { name: 'PrimeNG', Icon: SiPrimeng, color: '#10B981' },
  { name: 'RxJS', Icon: SiReactivex, color: '#B7178C' },
  { name: 'React', Icon: SiReact, color: '#61DAFB' },
  { name: 'Next.js', Icon: SiNextdotjs, color: '#000000' },
  { name: 'NestJS', Icon: SiNestjs, color: '#E0234E' },
  { name: 'Laravel', Icon: SiLaravel, color: '#FF2D20' },
  { name: 'PHP', Icon: SiPhp, color: '#777BB4' },
  { name: 'Node', Icon: SiNodedotjs, color: '#5FA04E' },
  { name: 'Express', Icon: SiExpress, color: '#000000' },
  { name: 'MySQL', Icon: SiMysql, color: '#4479A1' },
  { name: 'MongoDB', Icon: SiMongodb, color: '#47A248' },
  { name: 'Docker', Icon: SiDocker, color: '#2496ED' },
  { name: 'Vitest', Icon: SiVitest, color: '#6E9F18' },
  { name: 'JEST', Icon: SiJest, color: '#C21325' },
  { name: 'Sentry', Icon: SiSentry, color: '#362D59' },
  { name: 'Redux', Icon: SiRedux, color: '#764ABC' },
  { name: 'Tanstack Query', Icon: SiReactquery, color: '#FF4154' },
  { name: 'Tailwind', Icon: SiTailwindcss, color: '#06B6D4' },
  { name: 'Sass', Icon: SiSass, color: '#CC6699' },
  { name: 'Shadcn', Icon: SiShadcnui, color: '#000000' },
  { name: 'Mantine', Icon: SiMantine, color: '#339AF0' },
  { name: 'Figma', Icon: SiFigma, color: '#F24E1E' },
  { name: 'JavaScript', Icon: SiJavascript, color: '#F7DF1E' },
];
